export const INCREMENT_STATE = 'INCREMENT_NOMBRE';
export const DECREMENT_STATE = 'DECREMENT_NOMBRE';
export const ADD_NEW_USER = 'ADD_NEW_USER';
export const REMOVE_USER = 'REMOVE_USER';
export const EDIT_USER = 'EDIT_USER';
